services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    environment:
      - COMPOSITE_URL=http://composite-service:8000
    depends_on:
      - composite-service

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    # expose a port only for debugging; composite and gateway use the internal network
    ports:
      - "8005:8000"

  composite-service:
    build: ./composite-service
    container_name: composite-service
    environment:
      - AUTH_URL=http://auth-service:8000
      - AI_RECOMMENDATION_URL=http://ai-recommendation-wrapper:8000
      - PAYMENT_URL=http://payment-wrapper:8000
    depends_on:
      - auth-service
      - ai-recommendation-wrapper
      - payment-wrapper

  ai-recommendation-wrapper:
    build: ./wrappers/ai-recommendation-wrapper
    container_name: ai-recommendation-wrapper
    ports:
      - "8006:8000"
    env_file:
      - ./wrappers/ai-recommendation-wrapper/.env
  payment-wrapper:
    build: ./wrappers/payment-wrapper
    container_name: payment-wrapper
    ports:
     - "8007:8000"
    env_file:
     - ./wrappers/payment-wrapper/.env

  calendar-wrapper:
    build: ./wrappers/calendar-wrapper
    container_name: calendar-wrapper
    ports:
     - "8008:8000"
