services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    environment:
      - COMPOSITE_URL=http://composite-service:8000
    depends_on:
      - composite-service

  user-service:
    build: ./services/user-service
    container_name: user-service
    # expose a port only for debugging; composite and gateway use the internal network
    ports:
      - "8005:8000"

  composite-service:
    build: ./composite-service/make-booking-composite-service
    container_name: make-booking-composite-service
    environment:
      - AUTH_URL=http://auth-service:8000
      - AI_RECOMMENDATION_URL=http://ai-recommendation-wrapper:8000
      - PAYMENT_URL=http://payment-wrapper:8000
    depends_on:
      - user-service
      - ai-recommendation-wrapper
      - payment-wrapper

  ai-recommendation-wrapper:
    build: ./wrappers/ai-recommendation-wrapper
    container_name: ai-recommendation-wrapper
    ports:
      - "8006:8000"

  payment-wrapper:
    build: ./wrappers/payment-wrapper
    container_name: payment-wrapper
    ports:
     - "8007:8000"

  # ai-recommendation-wrapper:
  #   build: ./wrappers/ai-recommendation-wrapper
  #   container_name: ai-recommendation-wrapper
  #   ports:
  #     - "8006:8000"
  #   env_file:
  #     - ./wrappers/ai-recommendation-wrapper/.env
  # payment-wrapper:
  #   build: ./wrappers/payment-wrapper
  #   container_name: payment-wrapper
  #   ports:
  #    - "8007:8000"
  #   env_file:
  #    - ./wrappers/payment-wrapper/.env
  #
  calendar-service:
    build:
      context: .
      dockerfile: ./services/calendar-service/Dockerfile
    container_name: calendar-service
    ports:
     - "8009:8000"

  notification-service:
    build:
      context: .
      dockerfile: ./services/notification_service/Dockerfile
    container_name: notification-service
    ports:
     - "8010:8000"

  activity-service:
    build:
      context: .
      dockerfile: ./services/activity-service/Dockerfile
    container_name: activity-service
    ports:
     - "8011:8000"

  quiz-service:
    build:
      context: .
      dockerfile: ./services/quiz-service/Dockerfile
    container_name: quiz-service
    ports:
     - "8012:8000"